### ISSUE TITLE
Error: dynamic exception specifications are deprecated in C++11

### ISSUE THREAD

**Issue by Weiming-Hu** [NREL/lk#11]
This issue is initially reported in [ticket](https://github.com/NREL/SAM/issues/116#issue-375172305)

I've played around and found [a quick fix](https://github.com/NREL/SAM/issues/116#issuecomment-434058485).

Please let me know if there is a better way to do this.

Thank you
Weiming

**Comment by nickdiorio** [comment]
@Weiming-Hu , thank you for bring this to our attention.  My guess is that since you are on Ubuntu 18 using a newer compiler than we've tested with, the compiler has added warnings indicating these deprecations: https://stackoverflow.com/questions/50254641/dynamic-exception-specifications-are-deprecated 

Your solution is temporarily the fastest (to disable `-Werrror`), though long term we should go through and address these one by one

**Comment by nickdiorio** [comment]
We will leave this ticket open until the warnings have been addressed.

**Comment by Weiming-Hu** [comment]
Thank you. I'm now using SAM without a problem. I leave this ticket for you to decide when to close.
